# Translation of Odoo Server.
# This file contains the translation of the following modules:
#	* l10n_it_fatturapa_pec_cron
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 8.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-01-28 18:21+0000\n"
"PO-Revision-Date: 2019-01-28 18:21+0000\n"
"Last-Translator: <>\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: \n"

#. module: l10n_it_fatturapa_pec_cron
#: view:website:l10n_it_fatturapa_pec_cron.email_template_invoices_with_errors_view
msgid "Dear"
msgstr ""

#. module: l10n_it_fatturapa_pec_cron
#: model:ir.model,name:l10n_it_fatturapa_pec_cron.model_fatturapa_attachment_out
msgid "E-invoice Export File"
msgstr ""

#. module: l10n_it_fatturapa_pec_cron
#: code:addons/l10n_it_fatturapa_pec_cron/models/account_invoice.py:27
#, python-format
msgid "E-invoice errors marked as resolved"
msgstr ""

#. module: l10n_it_fatturapa_pec_cron
#: code:addons/l10n_it_fatturapa_pec_cron/models/fatturapa_attachment_out.py:81
#, python-format
msgid "Error during E-invoice export"
msgstr ""

#. module: l10n_it_fatturapa_pec_cron
#: help:account.invoice,fatturapa_out_error:0
#: code:addons/l10n_it_fatturapa_pec_cron/models/account_invoice.py:18
#, python-format
msgid "If is set to true, then invoice had issues during last export via cron"
msgstr ""

#. module: l10n_it_fatturapa_pec_cron
#: model:ir.model,name:l10n_it_fatturapa_pec_cron.model_account_invoice
msgid "Invoice"
msgstr ""

#. module: l10n_it_fatturapa_pec_cron
#: view:website:l10n_it_fatturapa_pec_cron.email_template_invoices_with_errors_view
msgid "Invoice number"
msgstr ""

#. module: l10n_it_fatturapa_pec_cron
#: view:account.invoice:l10n_it_fatturapa_pec_cron.view_invoice_form_fatturapa_pec_cron
msgid "Mark E-invoice errors as resolved"
msgstr ""

#. module: l10n_it_fatturapa_pec_cron
#: view:website:l10n_it_fatturapa_pec_cron.email_template_invoices_with_errors_view
msgid "Partner"
msgstr ""

#. module: l10n_it_fatturapa_pec_cron
#: model:email.template,subject:l10n_it_fatturapa_pec_cron.email_template_invoices_with_errors_qweb
msgid "Report: Electronic Invoices not generated"
msgstr ""

#. module: l10n_it_fatturapa_pec_cron
#: view:website:l10n_it_fatturapa_pec_cron.email_template_invoices_with_errors_view
msgid "Review them and fix related errors."
msgstr ""

#. module: l10n_it_fatturapa_pec_cron
#: view:account.invoice:l10n_it_fatturapa_pec_cron.view_account_invoice_fatturapa_out_pec_cron_filter
msgid "Show invoices with errors during automatic e-invoice export."
msgstr ""

#. module: l10n_it_fatturapa_pec_cron
#: view:website:l10n_it_fatturapa_pec_cron.email_template_invoices_with_errors_view
msgid "The system was not able to generate this list of invoices."
msgstr ""

#. module: l10n_it_fatturapa_pec_cron
#: code:addons/l10n_it_fatturapa_pec_cron/models/account_invoice.py:28
#, python-format
msgid "User %s has marked e-invoice errors as resolved"
msgstr ""

#. module: l10n_it_fatturapa_pec_cron
#: view:account.invoice:l10n_it_fatturapa_pec_cron.view_account_invoice_fatturapa_out_pec_cron_filter
msgid "With Issues"
msgstr ""

#. module: l10n_it_fatturapa_pec_cron
#: field:account.invoice,fatturapa_out_error:0
#: code:addons/l10n_it_fatturapa_pec_cron/models/account_invoice.py:17
#, python-format
msgid "With issues during last export"
msgstr ""

